### ISSUE TITLE
页面元素定位问题

### ISSUE THREAD

**Issue by ihx-rainbow** [VitoYane/yuque_create#1]
一开始一直卡在知识库首页，还以为是我参数配的有问题

后面发现 我的页面 class 不太一样
```
page.locator(".larkui-icon.icon-svg.BookCatalog-module_actionItem_gOq-V").click(timeout=5000)
```
这里我的页面是 ReaderLayout-module_actionItem_CbOzz

![image](https://user-images.githubusercontent.com/30643029/197999986-1032f08c-018f-46eb-99c3-b91b344d0e2d.png)
换一下之后正常了
感谢大佬！先撸他1000个

**Comment by VitoYane** [comment]
嗯嗯, 是的, 可能页面元素有随机命名
用xpath会精准一些. 我来调整一下代码
但是昨天听说改策略了, 每月100篇, 应该是够得了.
![image](https://user-images.githubusercontent.com/17432059/198166427-cba08aee-2bf9-4e18-9feb-289316f95bd6.png)

**Comment by VitoYane** [comment]
看了下, 是页面改版了, 新的class跟你写的一致
